[[connection]]
adapter="mysql"
type = "ssh"
name = "localhost"
host = "locahost"
port = "3306"
username = "root"
password = ""
database = ""

[[connection]]
adapter="mysql"
type = "standard"
name = "veramiko"
host = "locahost"
port = "3307"
username = "root"
password = ""
database = ""

[[connection]]
adapter="mysql"
type = "socket"
name = "ooyala"
socket = "/var/run/mysql.socket"
username = "root"
password = ""
database = ""

[debug]
level=5
